import type { Metadata } from 'next';
import PcPricing from './components/PcPricing';
import { detectServerDeviceType } from '../../utils/getDeviceType';
import { Test } from '@/app/[lng]/test';
import { useTranslation } from '../../i18n';

// export const metadata: Metadata = {
//   title: 'DSers Plans and Pricing - DSers',
//   description: 'Generated by create next app',
// };
type ParamsType = {
  params: Record<string, string>;
};

export default async function Page({ params: { lng } }: ParamsType) {
  // const { isMobile } = detectServerDeviceType();
  const { t } = await useTranslation(lng);

  return (
    <>
      <Test lng={lng} />
      {/* <PcPricing lng={lng} isMobile={isMobile} /> */}
    </>
  );
}
